import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { requireAdmin } from "@/lib/auth";
import { createAdminClient } from "@/lib/supabase/admin";
import { tshirtReceiptUrl } from "@/lib/tshirts";
import { AdminShell } from "@/components/admin/AdminShell";
import { TshirtReviewActions } from "@/components/admin/TshirtReviewActions";
import { TSHIRT_STATUS_LABEL } from "@/lib/tshirts-shared";
import { formatDateTime } from "@/lib/format";
import { formatLkr } from "@/lib/tickets-shared";
export const metadata: Metadata = { title: "T-shirt order", robots: { index: false } }; export const dynamic = "force-dynamic";
export default async function AdminTshirtOrder({ params }: { params: Promise<{ id: string }> }) { const session = await requireAdmin(); const db = createAdminClient(); const { data: order } = await db.from("tshirt_orders").select("*").eq("id", (await params).id).maybeSingle(); if (!order) notFound(); const receiptUrl = await tshirtReceiptUrl(order.receipt_path); const pdf = order.receipt_path.toLowerCase().endsWith(".pdf"); return <AdminShell email={session.email} role={session.role}><Link href="/admin/tshirts" className="font-sans text-sm text-accent-strong hover:underline">← All T-shirt orders</Link><h1 className="mt-3 text-2xl text-ink">{order.reference}</h1><p className="mt-1 font-sans text-sm text-ink-muted">{TSHIRT_STATUS_LABEL[order.status]} · {formatDateTime(order.created_at)}</p><div className="mt-6 grid gap-6 md:grid-cols-2"><div className="rounded-card border border-hairline p-4 font-sans text-sm"><h2 className="text-xs font-semibold uppercase tracking-wider text-ink-muted">Buyer details</h2><p className="mt-3 text-ink">{order.name}</p><p className="text-ink-muted">{order.registration_number}</p><p className="text-ink-muted">{order.faculty}</p><a className="mt-2 block text-accent-strong" href={`mailto:${order.email}`}>{order.email}</a><p className="text-ink-muted">{order.phone}</p><p className="mt-3 text-ink">Size <strong>{order.tshirt_size}</strong> · Quantity <strong>{order.quantity}</strong> · {formatLkr(order.amount_lkr)}</p>{order.review_note && <p className="mt-3 rounded-field bg-canvas-raised p-2 text-ink-muted">Note: {order.review_note}</p>}{order.collected_by && <p className="mt-3 text-xs text-ink-muted">Reviewed by {order.collected_by}{order.collected_at ? ` on ${formatDateTime(order.collected_at)}` : ""}</p>}</div><div className="rounded-card border border-hairline p-4"><h2 className="font-sans text-xs font-semibold uppercase tracking-wider text-ink-muted">Payment receipt</h2>{receiptUrl ? pdf ? <a href={receiptUrl} target="_blank" rel="noopener noreferrer" className="mt-3 inline-block text-sm text-accent-strong underline">Open receipt (PDF)</a> : <a href={receiptUrl} target="_blank" rel="noopener noreferrer"><img src={receiptUrl} alt="Payment receipt" className="mt-3 max-h-96 w-full rounded-field object-contain ring-1 ring-hairline" /></a> : <p className="mt-3 text-sm text-red-600">Receipt file not found.</p>}</div></div>{order.status === "pending_review" && <div className="mt-6"><TshirtReviewActions orderId={order.id} /></div>}</AdminShell>; }
