"use client";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { Button } from "@/components/ui/Button";
export function TshirtReviewActions({ orderId }: { orderId: string }) {
  const router = useRouter(); const [checked, setChecked] = useState(false); const [note, setNote] = useState(""); const [busy, setBusy] = useState<"collect" | "reject" | null>(null); const [error, setError] = useState<string | null>(null);
  async function act(action: "collect" | "reject") { if (action === "collect" && !checked) return; setBusy(action); setError(null); try { const r = await fetch("/api/admin/tshirts", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action, orderId, note }) }); const d = await r.json() as { ok: boolean; error?: string }; if (d.ok) router.refresh(); else setError(d.error ?? "Something went wrong."); } catch { setError("We couldn't reach the server."); } finally { setBusy(null); } }
  return <div className="rounded-card border border-hairline p-4"><h2 className="text-lg text-ink">Confirm manual collection</h2><p className="mt-1 font-sans text-sm text-ink-muted">Check the receipt against the payment you received before confirming.</p><label className="mt-4 flex gap-2 font-sans text-sm text-ink"><input type="checkbox" checked={checked} onChange={e => setChecked(e.target.checked)} className="mt-0.5 accent-accent" />I have confirmed that this payment was collected.</label><label className="mt-4 flex flex-col gap-1 font-sans text-sm text-ink-muted">Review note (optional)<input value={note} onChange={e => setNote(e.target.value)} className="rounded-field border border-hairline bg-transparent px-3 py-1.5 text-ink" /></label>{error && <p className="mt-3 text-sm text-red-600">{error}</p>}<div className="mt-4 flex gap-3"><Button onClick={() => act("collect")} disabled={!checked || busy !== null} loading={busy === "collect"}>Mark payment collected</Button><Button variant="ghost" onClick={() => act("reject")} disabled={busy !== null} loading={busy === "reject"}>Reject</Button></div></div>;
}
